name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
    - name: Installing packages
      run: sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev libudev-dev libopenal-dev libvorbis-dev libflac++-dev libxrandr-dev

    - name: Cloning repository
      uses: actions/checkout@v2
      with:
        path: main_repo

    - name: Caching SFML
      uses: actions/cache@v2
      env:
        cache-name: cache-sfml-r
      with:
        path: sfml_repo
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-${{ github.run_id }}
          ${{ runner.os }}-${{ env.cache-name }}-
    
    - name: Cloning SFML
      shell: bash
      run: |
        [ ! -d sfml_repo ] && git clone --depth 1 https://github.com/SFML/SFML.git sfml_repo || true
        cd sfml_repo && git pull

    - name: Building SFML
      shell: bash
      run: |
        cd sfml_repo
        mkdir -p build install
        cd build
        #cmake -DCMAKE_INSTALL_PREFIX=../install ..
        cmake ..
        cmake --build .
        #cmake --install .
        sudo cmake --install .

    - name: Building Projects
      shell: bash
      run: |
        cd main_repo
        mkdir -p build install
        cd build
        ls $GITHUB_WORKSPACE/sfml_repo/install/lib/cmake/SFML
        #cmake -DCMAKE_INSTALL_PREFIX=../install -DSFML_DIR=$GITHUB_WORKSPACE/sfml_repo/install/lib/cmake/SFML  ..
        cmake -DCMAKE_INSTALL_PREFIX=../install ..
        cmake --build .
        cmake --install .
        
    - name: Building AppImage
      shell: bash
      run: |
        cd main_repo
        mkdir appimage_packaging
        cd appimage_packaging
        ../misc/build_appimage.sh
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: appimage_dir
        path: main_repo/appimage_packaging
