name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
    - name: Installing packages
      run: sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev libudev-dev libopenal-dev libvorbis-dev libflac++-dev libxrandr-dev libsfml-dev

    - name: Cloning repository
      uses: actions/checkout@v2
      with:
        path: main_repo

    - name: Building Projects
      shell: bash
      run: |
        cd main_repo
        mkdir -p build install
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=../install ..
        cmake --build .
        cmake --install .
        
    - name: Building AppImage
      shell: bash
      run: |
        cd main_repo
        mkdir appimage_packaging
        cd appimage_packaging
        ../misc/build_appimage.sh
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: appimage_dir
        path: main_repo/appimage_packaging
