name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
    - name: Installing packages
      run: sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev libudev-dev libopenal-dev libvorbis-dev libflac++-dev libxrandr-dev

    - name: Cloning repository
      uses: actions/checkout@v2
      with:
        path: main_repo

    - name: Caching SFML
      uses: actions/cache@v2
      env:
        cache-name: cache-sfml
      with:
        path: sfml_repo
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-${{ github.run_id }}
          ${{ runner.os }}-${{ env.cache-name }}-
    
    - name: Cloning SFML
      shell: bash
      run: |
        [ ! -d sfml_repo ] && git clone --depth 1 https://github.com/SFML/SFML.git sfml_repo || true
        cd sfml_repo && git pull

    - name: Building SFML
      shell: bash
      run: |
        cd sfml_repo
        mkdir -p build install
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=../install ..
        cmake --build .
        cmake --install .

    - name: Building Projects
      shell: bash
      run: |
        cd main_repo
        mkdir -p build install
        cd build
        pwd
        ls ..
        ls ../..
        ls ../../sfml_repo
        ls ../../sfml_repo/install
        ls ../../sfml_repo/install/lib64
        ls ../../sfml_repo/install/lib64/cmake
        ls ../../sfml_repo/install/lib64/cmake/SFML
        cmake -DCMAKE_INSTALL_PREFIX=../install -DSFML_DIR=../../sfml_repo/install/lib64/cmake/SFML  ..
        cmake --build .
        cmake --install .
