name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
    - name: Installing packages
      run: |
        # sudo apt-get build-dep libsfml-dev
        wget https://www.sfml-dev.org/files/SFML-2.5.1-linux-gcc-64-bit.tar.gz
        tar -xf SFML-2.5.1-linux-gcc-64-bit.tar.gz
        sudo apt-get install emacs

    - name: Cloning repository
      uses: actions/checkout@v2
      with:
        path: main_repo

    - name: Building Projects
      shell: bash
      run: |
        cd main_repo
        mkdir -p build install
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release -DSFML_ROOT=../../SFML-2.5.1 ..
        cmake --build .
        cmake --install .
        
    - name: Building AppImage
      shell: bash
      run: |
        cd main_repo
        ./misc/build_appimage.sh
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: SamuelMenu
        path: main_repo/appimage_packaging/SamuelMenu.AppImage
